const ShortUniqueId = require('short-unique-id');
const URL = require('../models/url');


const uid = new ShortUniqueId();



async function handleGenerateShortUrl(req, res) {
    const body = req.body;
    console.log(body);
    const individualid = uid.rnd();
    console.log(`this is unique id generated by external model ${individualid}`);

    if (!body.url) {
        return res.status(400).json({
            'error': 'url is empty'
        });
    }
    await URL.create({
        shortid: individualid,
        redirectUrl: body.url,
        visitHistory: []
    });
    return res.json({
        'id': individualid
    });
}


module.exports = {
    handleGenerateShortUrl
}